### ISSUE TITLE
If a player name is too long, !rank will not display the name correctly

### ISSUE THREAD

**Issue by BakxY** [BakxY/DiscordApexBot#12]
**Description**
If a player name is longer than envisaged in Apex Legends, the name will be cut off on the left and right.

**To Reproduce**
1. make a valid !rank request with a too long name (ex: `nvmessiahttv`)
2. The image will have the name cut off (see attachment)

**Expected behavior**
The name should scale, depending on its length

![output](https://user-images.githubusercontent.com/79839223/155574226-1da5036e-95d8-419b-87fb-bee0a383d719.png)

**Comment by FischerTG** [comment]
![image](https://user-images.githubusercontent.com/76223353/155875117-4dbf26b0-9eac-49cc-a5fb-3602f4513e1e.png)
